# Generated by Django 5.0.3 on 2025-04-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0003_remove_appointment_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor_id', 'date_of_appointment', 'time_of_appointment')},
        ),
    ]
